<a href="https://colab.research.google.com/github/shawnteh1711/tensorflow/blob/master/TensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Import Libraries

In [ ]:
import tensorflow as tf
print("TensorFlow version: ", tf.__version__)

TensorFlow version:  2.15.0


In [ ]:
import numpy as np
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

Load and Preprocess Data

In [ ]:
data = load_breast_cancer()
X, y = (data.data, data.target)

# print(data)
# print("feature: ", X)
# print("target: ", y)
feature_names = data.feature_names
# print("feature_names: ", feature_names)
target_names = data.target_names
# print("target_names: ", target_names)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
# print("X_train: ", X_train)
# print("X_test: ", X_test)
# print("y_train: ", y_train)
# print("y_test: ", y_test)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
# print("X_train: ", X_train)
X_test = scaler.transform(X_test)

X_test:  [[1.247e+01 1.860e+01 8.109e+01 ... 1.015e-01 3.014e-01 8.750e-02]
 [1.894e+01 2.131e+01 1.236e+02 ... 1.789e-01 2.551e-01 6.589e-02]
 [1.546e+01 1.948e+01 1.017e+02 ... 1.514e-01 2.837e-01 8.019e-02]
 ...
 [1.152e+01 1.493e+01 7.387e+01 ... 9.608e-02 2.664e-01 7.809e-02]
 [1.422e+01 2.785e+01 9.255e+01 ... 8.219e-02 1.890e-01 7.796e-02]
 [2.073e+01 3.112e+01 1.357e+02 ... 1.659e-01 2.868e-01 8.218e-02]]


Build a TensorFlow Model

In [ ]:
# print("X_train.shape[1]: ", X_train.shape[1])
model = tf.keras.Sequential([
    tf.keras.layers.Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# help(model.compile)

Help on method compile in module keras.src.engine.training:

compile(optimizer='rmsprop', loss=None, metrics=None, loss_weights=None, weighted_metrics=None, run_eagerly=None, steps_per_execution=None, jit_compile=None, pss_evaluation_shards=0, **kwargs) method of keras.src.engine.sequential.Sequential instance
    Configures the model for training.
    
    Example:
    
    ```python
    model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3),
                  loss=tf.keras.losses.BinaryCrossentropy(),
                  metrics=[tf.keras.metrics.BinaryAccuracy(),
                           tf.keras.metrics.FalseNegatives()])
    ```
    
    Args:
        optimizer: String (name of optimizer) or optimizer instance. See
          `tf.keras.optimizers`.
        loss: Loss function. May be a string (name of loss function), or
          a `tf.keras.losses.Loss` instance. See `tf.keras.losses`. A loss
          function is any callable with the signature `loss = fn(y_true,
  

Train the Model

In [ ]:
model.fit(X_train, y_train, epochs=10, batch_size=32, validation_split=0.2)

Epoch 1/10
12/12 [==============================] - 2s 24ms/step - loss: 0.4800 - accuracy: 0.8297 - val_loss: 0.3613 - val_accuracy: 0.8901
Epoch 2/10
12/12 [==============================] - 0s 5ms/step - loss: 0.3025 - accuracy: 0.9231 - val_loss: 0.2587 - val_accuracy: 0.9451
Epoch 3/10
12/12 [==============================] - 0s 6ms/step - loss: 0.2227 - accuracy: 0.9451 - val_loss: 0.2084 - val_accuracy: 0.9451
Epoch 4/10
12/12 [==============================] - 0s 5ms/step - loss: 0.1791 - accuracy: 0.9478 - val_loss: 0.1814 - val_accuracy: 0.9451
Epoch 5/10
12/12 [==============================] - 0s 5ms/step - loss: 0.1536 - accuracy: 0.9533 - val_loss: 0.1646 - val_accuracy: 0.9451
Epoch 6/10
12/12 [==============================] - 0s 5ms/step - loss: 0.1358 - accuracy: 0.9588 - val_loss: 0.1530 - val_accuracy: 0.9451
Epoch 7/10
12/12 [==============================] - 0s 5ms/step - loss: 0.1219 - accuracy: 0.9670 - val_loss: 0.1440 - val_accuracy: 0.9451
Epoch 8/10
12/12 [=

Evaluate the Model

In [ ]:
loss, accuracy = model.evaluate(X_test, y_test)
print(f"Test Loss: {loss}, Test Accuracy: {accuracy}")

4/4 [==============================] - 0s 4ms/step - loss: 0.0789 - accuracy: 0.9825
Test Loss: 0.07886411249637604, Test Accuracy: 0.9824561476707458


Make Predictions

In [ ]:
predictions = model.predict(X_test)
print(predictions)

4/4 [==============================] - 0s 3ms/step
[[8.20825458e-01]
 [3.20909638e-03]
 [4.72218990e-02]
 [9.64369476e-01]
 [9.90518987e-01]
 [2.50552466e-06]
 [3.42747990e-05]
 [9.94342566e-02]
 [4.84712481e-01]
 [9.85735118e-01]
 [9.23135340e-01]
 [7.99553245e-02]
 [9.63280737e-01]
 [1.85644850e-01]
 [9.93080199e-01]
 [5.08907018e-03]
 [9.81377125e-01]
 [9.98025537e-01]
 [9.99681473e-01]
 [6.31794508e-04]
 [7.55842805e-01]
 [9.66998458e-01]
 [3.02332792e-05]
 [9.97666299e-01]
 [9.79325175e-01]
 [9.71706867e-01]
 [9.84033346e-01]
 [9.58969355e-01]
 [9.71937656e-01]
 [7.90643157e-04]
 [9.45173740e-01]
 [9.95831251e-01]
 [9.71128821e-01]
 [9.80114222e-01]
 [9.94415998e-01]
 [9.86805320e-01]
 [2.68486589e-01]
 [9.74548638e-01]
 [6.60349289e-03]
 [8.09021950e-01]
 [9.88295197e-01]
 [4.46174331e-02]
 [9.71320987e-01]
 [9.90192413e-01]
 [9.08904791e-01]
 [9.73621428e-01]
 [9.94625688e-01]
 [9.92217541e-01]
 [9.35350299e-01]
 [9.73772168e-01]
 [9.55911446e-03]
 [2.97960738e-04]
 [5.83565056e